backend:
  name: github
  repo: fedsa/fedsa-website
  branch: master
media_folder: public/images
collections:
  - label: Pages
    name: Pages
    files:
      - name: homepage
        label: Homepage
        file: public/data/homepage.json
        fields:
          - name: left_column
            label: Left Column
            widget: list
            fields: 
              - name: title
                label: title
                widget: string
              - name: body
                label: body
                widget: markdown
          - name: middle_column
            label: Middle Column
            widget: list
            fields: 
              - name: title
                label: title
                widget: string
              - name: body
                label: body
                widget: markdown
          - name: right_column
            label: right Column
            widget: list
            fields: 
              - name: title
                label: title
                widget: string
              - name: body
                label: body
                widget: markdown
      - name: members
        label: Members
        file: public/data/members.json
        fields:
          - name: members
            label: Members
            widget: list
            fields: 
              - name: full_name
                label: Full name
                widget: string
              - name: image
                label: Image
                widget: image
              - name: biography
                label: Biography
                widget: text
      - name: constitution
        label: Constitution
        file: public/data/constitution.json
        fields: 
          - name: text
            label: Text
            widget: markdown

      - label: Projects
        name: projects
        file: public/data/projects.json
        fields:
          - label: Projects
            name: projects
            widget: list
            fields:
              - label: Title
                name: title
                widget: string
                required: true
              - label: Description
                name: description
                widget: text
                required: true
              - label: Link
                name: link
                widget: text
                required: true