backend:
  name: github
  repo: fedsa/fedsa-website
  branch: netlify-cms-setup
media_folder: uploads
collections:
  - label: Pages
    name: Pages
    files:
      - name: homepage
        label: Homepage
        file: public/data/homepage.json
        fields:
          - name: left_column
            label: Left Column
            widget: list
            fields: 
              - name: title
                label: title
                widget: string
              - name: body
                label: body
                widget: markdown
          - name: middle_column
            label: Middle Column
            widget: list
            fields: 
              - name: title
                label: title
                widget: string
              - name: body
                label: body
                widget: markdown
          - name: right_column
            label: right Column
            widget: list
            fields: 
              - name: title
                label: title
                widget: string
              - name: body
                label: body
                widget: markdown
      - name: members
        label: Members
        file: public/data/members.json
        fields:
          - name: members
            label: Members
            widget: list
            fields: 
              - name: image
                label: Image
                widget: image
              - name: full_name
                label: Full name
                widget: string
              - name: biography
                label: Biography
                widget: text