backend:
  name: github
  repo: fedsa/fedsa-website
media_folder: uploads
collections:
  - name: "homepage" # Used in routes, e.g., /admin/collections/blog
    identifier_field: left_column
    extension: json
    label: "Homepage" # Used in the UI
    folder: "public/data" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: homepage.json # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - name: left_column
        label: left_column
        widget: list
        fields: 
          - name: title
            label: title
            widget: string
          - name: body
            label: body
            widget: markdown